services:
  astro-app:
    image: ghcr.io/k1nd4sus/k1nd4sus.github.io:latest
    container_name: astro-app
    environment:
      HOST: 0.0.0.0
      PORT: 4321
    restart: unless-stopped
    networks:
      - npm-net

networks:
  npm-net:
    external: true
