export interface TeamMember {
  name: string;
  university: string;
  role: string;
  tags: string[];
  username?: string;
  github?: string;
  telegram?: string;
  linkedin?: string;
  instagram?: string;
  email?: string;
  link?: string;
}

export const teamMembers: TeamMember[] = [
  {
    name: "Samuele Manclossi",
    university: "UniMi (University of Milan)",
    role: "🜲 President & Co-Founder",
    tags: ["rev", "crypto", "misc"],
    username: "S-Mancl",
    linkedin: "https://www.linkedin.com/in/samuele-manclossi/",
    telegram: "https://t.me/s3m_mancl",
    email: "mailto:presidency@k1nd4sus.it",
  },
  {
    name: "Cristian Salvi",
    university: "UniMi (University of Milan)",
    role: "Vicepresident & Treasurer",
    tags: ["pwn", "rev"],
    github: "https://github.com/5alv1",
    telegram: "https://t.me/salv1cri",
    email: "mailto:treasury@k1nd4sus.it",
    username: "5alv1.py",
  },
  {
    name: "Andrea Lunghi",
    university: "UniMi (University of Milan)",
    role: "Vicepresident & CTF",
    tags: ["web", "misc"],
    username: "andre",
    linkedin: "https://www.linkedin.com/in/andrea-lunghi/",
    link: "https://andrealungh1.github.io/",
    email: "mailto:ctf@k1nd4sus.it ",
  },
  {
    name: "Niccolò Volontè",
    university: "UniMi (University of Milan)",
    role: "Vicepresident & Social-media",
    tags: ["web", "misc", "network"],
    username: "niccolovlnt",
    linkedin: "https://www.linkedin.com/in/niccol%C3%B3-volont%C3%A8-a03108252/",
    telegram: "https://t.me/niccolovlnt",
    link: "https://me.nicklab.it/",
    github: "https://github.com/niccolovlnt",
    email: "mailto:public.communications@k1nd4sus.it",
  },
  {
    name: "Alessandro Mellone",
    role: "Vicepresident & Events",
    university: "UniMi (University of Milan)",
    tags: ["misc", "network"],
    username: "melloc",
    email: "mailto:events@k1nd4sus.it",
    linkedin: "https://www.linkedin.com/in/alessandro-mellone-2983951bb/",
    instagram: "https://www.instagram.com/ale.mellone/",
    telegram: "https://t.me/melloc03",
  },
  {
    name: "Emma Privitera",
    role: "Admin & Webdev",
    university: "UniMi (University of Milan)",
    tags: ["web", "osint"],
    username: "Privitorta",
    github: "https://github.com/privitorta",
    linkedin: "https://www.linkedin.com/in/emmaprivitera/",
    telegram: "https://t.me/t3staocr0ce",
    instagram: "https://www.instagram.com/privitorta/",
    email: "mailto:emma.privitera.505@gmail.com",
  },
  {
    name: "Pavit Singh",
    role: "Admin & Activity Manager",
    university: "UniMi (University of Milan)",
    tags: ["rev", "misc"],
    username: "dhn_00",
    linkedin: "https://www.linkedin.com/in/pavit-singh-1075a823b/",
  },
  {
    name: "Natalia Daniello Lopez",
    role: "Admin & Vice-Treasurer",
    university: "UniMi (University of Milan)",
    tags: ["forensics"],
    username: "Ntlia",
    linkedin: "https://www.linkedin.com/in/natalia-daniello",
  },
  {
    name: "Edoardo Bavaro",
    role: "Admin & Group Manager",
    university: "UniMi (University of Milan)",
    tags: ["web", "osint", "forensics"],
    username: "0xRose",
    linkedin: "https://www.linkedin.com/in/edoardo-bavaro-1178a719b/",
    github: "https://github.com/EddyDevProject",
    telegram: "https://t.me/RipEddy",
    link: "https://edoardobavaro.me/",
    email: "mailto:me@edoardobavaro.me",
  },
  {
    name: "Mattia Perfumo",
    role: "EX President & Co-Founder",
    university: "KTH (Kungliga Tekniska Högskolan)",
    tags: ["web", "osint", "network"],
    username: "perfumo",
    link: "https://mattiaperfumo.it/",
    github: "https://github.com/mperf",
    linkedin: "https://www.linkedin.com/in/mattia-perfumo-08201013a/",
    email: "mperf21@proton.me",
    telegram: "https://t.me/Perf21"
  },
  {
    name: "Tiziano Radicchi",
    role: "EX Vicepresident & Co-Founder",
    university: "PoliTo (Polytechnic University of Turin)",
    tags: ["rev", "forensics"],
    username: "Tiz314",
    link: "https://tiz314.it/",
    github: "https://github.com/tiz314",
  },
  {
    name: "Matteo Zoia",
    role: "EX Vicepresident & Co-Founder",
    university: "PhD @ UniMi, Consultant @ Spike Reply",
    tags: ["pwn", "rev", "hardware"],
    username: "teozoia",
    linkedin: "https://it.linkedin.com/in/matteozoia",
  },
  {
    name: "Mirco Picca",
    role: "EX Vicepresident",
    university: "Penetration Tester @ SecureNetwork",
    tags: ["pwn", "web", "rev"],
    username: "Kribas",
    github: "https://github.com/Kr1bas",
    linkedin: "https://www.linkedin.com/in/mirco-picca-577647211",
  },
  {
    name: "Marco Galvagni",
    role: "Co-Founder",
    university: "Security Engineer @ CybergON",
    tags: ["web", "crypto"],
    username: "M4RC02U1F4A4",
    linkedin: "https://www.linkedin.com/in/marco-galvagni/",
    github: "https://github.com/M4RC02U1F4A4"
  },
  {
    name: "Edoardo della Rossa",
    role: "Co-Founder",
    university: "PhD Student @ TU/e",
    tags: ["rev", "binary", "hardware"],
    username: "Miniman",
    telegram: "https://t.me/Miniman",
    linkedin: "https://www.linkedin.com/in/edoardo-della-rossa-888748254/",
  },
  {
    name: "Alberto Ovena",
    role: "Member",
    university: "PoliTo (Polytechnic University of Turin)",
    tags: ["crypto"],
    username: "mightygibbon",
    github: "https://github.com/mightygibbon",
    linkedin: "https://www.linkedin.com/in/alberto-ovena/",
  },
  {
    name: "Melissa Moioli",
    role: "Member",
    university: "PoliTo (Polytechnic University of Turin)",
    tags: ["rev", "forensics", "binary"],
    github: "https://github.com/Rebel-Nightmare",
    linkedin: "https://www.linkedin.com/in/melissa-m-839739254",
    username: "RebelNightmare_",
  },
  {
    name: "Aleksandar Ivanov",
    role: "Member",
    university: "Penetration Tester @ Capgemini",
    tags: ["web", "misc", "pwn"],
    username: "IvAlexEv",
    link: "https://ivalexev.gitbook.io/rednote",
    linkedin: "https://www.linkedin.com/in/IvAlexEv",
    github: "https://github.com/IvAlexEv",
  },
  {
    name: "Edoardo",
    role: "Member",
    university: ". . .",
    tags: ["crypto", "misc", "osint"],
    username: "Veprion",
    telegram: "https://t.me/Veprion",
  },
  {
    name: "Andrea Sacchi",
    role: "Member",
    university: "UniMi (University of Milan)",
    tags: ["web", "rev"],
    username: "alsacchi",
    link: "https://www.0x41414141.it/",
    github: "https://github.com/alsacchi",
    telegram: "https://t.me/alsacchi",
    linkedin: "https://www.linkedin.com/in/andrea-0x41414141/",
  },
  {
    name: "Pietro Lepori",
    role: "Member",
    university: ". . .",
    tags: ["crypto"],
    username: "Pi",
    linkedin: "https://www.linkedin.com/in/pietro-lepori/",
  },
  {
    name: "Rocco Amico",
    role: "Member",
    university: "UniMi (University of Milan)",
    tags: ["misc", "osint"],
    username: "[kuom]",
    github: "https://github.com/ohkuom"
  },
  {
    name: "Vincenzo",
    role: "Member",
    university: ". . .",
    tags: ["web", "misc"],
    username: "Sniirful",
    github: "https://github.com/sniirful",
  }
];
